name: Build Executables

on:
  push:
    branches:
      - development  # Trigger when pushing to the 'development' branch

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Run on each OS in the matrix

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Only build on Linux and Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Use Python 3.x (specify version if needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build the executable with PyInstaller
        run: |
          pyinstaller --onefile run_cyoag.py

      - name: List dist directory contents (cross-platform)
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell -Command "Get-ChildItem dist"
          else
            ls -alh dist/
          fi

      - name: Archive the executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv dist/run_cyoag cyoag-linux  # Rename executable for Linux
          tar -czf cyoag-linux.tar.gz cyoag-linux  # Archive Linux executable

      - name: Archive the executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          move dist\run_cyoag.exe cyoag-windows.exe  # Use `move` instead of `mv` on Windows
          zip cyoag-windows.zip cyoag-windows.exe  # Zip the Windows executable

      - name: Upload Executable Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cyoag-executables
          path: |
            cyoag-linux.tar.gz
            cyoag-windows.zip

      - name: Get latest tag and increment version
        id: get_version
        run: |
          latest_tag=$(git tag -l | sort -V | tail -n 1)
          if [[ -z "$latest_tag" ]]; then
            new_tag="v1.0.0"
          else
            version_parts=(${latest_tag//./ })
            patch_version=${version_parts[2]}
            new_patch_version=$((patch_version + 1))
            new_tag="v${version_parts[0]}.${version_parts[1]}.$new_patch_version"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch existing tags to ensure we're working with the latest
        run: |
          git fetch --tags

      - name: Debug - List Tags (before creating release)
        run: |
          echo "Listing all tags..."
          git tag -l  # List all tags to check if the tag exists

      - name: Create a new Git tag
        run: |
          git tag -a ${{ env.new_tag }} -m "Release version ${{ env.new_tag }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} --tags

      - name: Create GitHub Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cyoag-linux.tar.gz
            cyoag-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required to create a release and upload files
